Fixing

diff --git a/.github/workflows/deploy-command.yml b/.github/workflows/deploy-command.yml
--- a/.github/workflows/deploy-command.yml
+++ b/.github/workflows/deploy-command.yml
@@ -6,15 +6,15 @@ jobs:
   deploy:
     runs-on: windows-latest
     steps:
-      - name: Get vars
-        id: vars
-        run: |
-          $version="${{ github.event.client_payload.slash_command.args.named.version }}"
-          $env="${{ github.event.client_payload.slash_command.args.named.env }}"
-          if ([string]::IsNullOrEmpty($version)) { echo "Missing version arg"; exit 1; }
-          if ([string]::IsNullOrEmpty($env)) { echo "Missing env arg"; exit 1; }
-          echo "version=$version" >> $env:GITHUB_OUTPUT
-          echo "env=$env" >> $env:GITHUB_OUTPUT
+      # - name: Get vars
+      #   id: vars
+      #   run: |
+      #     $version="${{ github.event.client_payload.slash_command.args.named.version }}"
+      #     $env="${{ github.event.client_payload.slash_command.args.named.env }}"
+      #     if ([string]::IsNullOrEmpty($version)) { echo "Missing version arg"; exit 1; }
+      #     if ([string]::IsNullOrEmpty($env)) { echo "Missing env arg"; exit 1; }
+      #     echo "version=$version" >> $env:GITHUB_OUTPUT
+      #     echo "env=$env" >> $env:GITHUB_OUTPUT
 
       - name: Add reaction
         uses: peter-evans/create-or-update-comment@v2
