fix powershell

diff --git a/.github/workflows/deploy-command.yml b/.github/workflows/deploy-command.yml
--- a/.github/workflows/deploy-command.yml
+++ b/.github/workflows/deploy-command.yml
@@ -11,10 +11,11 @@ jobs:
         run: |
           version=${{ github.event.client_payload.slash_command.args.named.version }}
           env=${{ github.event.client_payload.slash_command.args.named.env }}
-          if [[ -z "$version" ]]; then echo "Missing version arg"; exit 1; fi
+          if ([string]::IsNullOrEmpty($version)) { echo "Missing version arg"; exit 1; }
+          if ([string]::IsNullOrEmpty($env)) { echo "Missing env arg"; exit 1; }
           if [[ -z "$env" ]]; then echo "Missing env arg"; exit 1; fi
-          echo "version=$version" >> $GITHUB_OUTPUT
-          echo "env=$env" >> $GITHUB_OUTPUT
+          echo "version=$version" >> $env:GITHUB_OUTPUT
+          echo "env=$env" >> $env:GITHUB_OUTPUT
 
       - name: Download ${{ env.APP_SERVICE_PROJECT }} Artifact
         uses: actions/download-artifact@v3
